- name: configure catalogue server
  become: yes
  hosts: catalogue
  tasks:
  - name: disabled and enabled nodejs 
    ansible.builtin.command: dnf module disable nodejs -y
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
     name: nodejs 
     state: present
  
  - name: create roboshop system user
    ansible.builtin.user:
     name: roboshop
     system: true
     shell: /sbin/nologin
     home: /app

  - name: create app directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: download the catalogue application
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
     dest: /tmp/catalogue.zip
     
  - name: unzip the catalogue application
    ansible.builtin.unarchive:
     src: /tmp/catalogue.zip
     dest: /app
     remote_src: yes

  - name: install npm package
    community.general.npm:
     path: /app

  - name: set catalogue service
    ansible.builtin.copy:
     src: catalogue.service
     dest: /etc/systemd/system/catalogue.service

  - name: systemctl demon reload
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: enable and start catalogue
    ansible.builtin.service:
     name: catalogue
     state: started
     enabled: yes
     
  - name: set mongodb repo
    ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
     name: mongodb-mongosh
     state: present
  - name: load the data
    ansible.builtin.shell: mongosh --host MONGODB-SERVER-IPADDRESS </app/db/master-data.js