- name: configure paymenet server
  become: yes
  hosts:
  tasks:
  - name: install python
    ansible.builtin.pip:
     name: python3-devel
     state: present
  - name: create roboshop system user
    ansible.builtin.user:
     name: roboshop
     shell: /sbin/nologin
     system: true
     home: /app
  - name: creat a directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: download the payment application
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
     dest: /tmp/payment.zip

  - name: unzip the payment application
    ansible.builtin.unarchive:
     src: /tmp/payment.zip
     dest: /app
     remote_src: yes

  - name: install dependencies
    ansible.builtin.pip:
      requirements: /app/requirements.txt

  - name: set the payment server
    ansible.builtin.copy:
     src: payment.service
     dest: /etc/systemd/system/payment.service

  - name: systemctl deamon reload
    ansible.builtin.systemd_service:
     daemon_reload: yes

  - name: enable and start payment
    ansible.builtin.service:
     name: payment
     state: started
     enabled: true