- name: comfigure shipping server
  become: yes
  hosts:
  tasks:
  - name: install maven
    ansible.builtin.dnf:
     name: maven
     state: present

  - name: create roboshop system user 
    ansible.builtin.user:
     name: roboshop
     system: true
     shell: /sbin/nologin
     home: /app

  - name: create a directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: download the shipping application
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
     dest: /tmp/shipping.zip

  - name: unzip the shipping application
    ansible.builtin.unarchive:
     src: /tmp/shipping.zip
     dest: /app
     remote_src: yes

  - name: install maven packages
    ansible.builtin.command: mvn clean package 
    args:
     chdir: /app
  
  - name: rename the target folder
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
     chdir: /app
  
  - name: copy the shipping service
    ansible.builtin.copy:
     src: shipping.service
     dest: /etc/systemd/system/shipping.service

  - name: deamon reload systemctl
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: enable start shipping
    ansible.builtin.service:
     name: shipping
     state: started
     enabled: yes

  - name: install mysql client
    ansible.builtin.dnf:
     name: mysql
     state: present
  
  - name: import the data from mysql
    community.mysql.mysql_db:
     login_user: root
     login_password: RoboShop@1
     state: import
     login_host: 
     target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql

  - name: restart the shipping
    ansible.builtin.service:
     name: shipping
     state: restarted


  

  
