- name: configure user server
  become: yes 
  hosts:
  tasks:
  - name: enable and disable nodejs 
    ansible.builtin.command: dnf module disable nodejs -y
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
     name: nodejs
     state: present

  - name: create roboshop system user
    ansible.builtin.user:
     name: roboshop
     system: true
     shell: /sbin/nologin
     home: /app

  - name: create a directory
    ansible.builtin.file:
     path: /app
     start: directory

  - name: download user application
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
     dest: /tmp/user.zip

  - name: unzip the user application
    ansible.builtin.unarchive:
     src: /tmp/user.zip
     dest: /app
     remote_src: yes
  
  - name: install npm package
    community.general.npm:
     path: /app

  - name: set the user service
    ansible.builtin.copy:
     src: user.service
     dest: /etc/systemd/system/user.service

  - name: enable and start user
    ansible.builtin.service:
     name: user
     state: started
     enabled: yes
     

  
    